#!/bin/bash
######################################################################
## File used for defining $PS1
## Adapted from "Nat's Colored Prompt"
## http://stackoverflow.com/posts/104036/revisions

bash_prompt_command() {
# Set up exit status notifier
EXITSTATUS="$?"
if [[ ${EXITSTATUS} -eq 0 ]]; then
    PC="\[\033[0;32m\]"
else
    PC="\[\033[0;31m\]"
fi

# How many characters of the $PWD should be kept
local pwdmaxlen=25
# Indicate that there has been dir truncation
local trunc_symbol=".."
local dir=${PWD##*/}
pwdmaxlen=$(( ( pwdmaxlen < ${#dir} ) ? ${#dir} : pwdmaxlen ))
NEW_PWD=${PWD/#$HOME/\~}
local pwdoffset=$(( ${#NEW_PWD} - pwdmaxlen ))
if [ ${pwdoffset} -gt "0" ]
then
    NEW_PWD=${NEW_PWD:$pwdoffset:$pwdmaxlen}
    NEW_PWD=${trunc_symbol}/${NEW_PWD#*/}
fi

export PC # TODO: Fix this so that dollarsign changes color per exit status
          # Problem is PS1 is expanded only once, upon shell instantiation ???
}

bash_prompt() {
local NONE="\[\033[0m\]"    # unsets color to term's fg color

# regular colors
local K="\[\033[0;30m\]"    # black
local R="\[\033[0;31m\]"    # red
local G="\[\033[0;32m\]"    # green
local Y="\[\033[0;33m\]"    # yellow
local B="\[\033[0;34m\]"    # blue
local M="\[\033[0;35m\]"    # magenta
local C="\[\033[0;36m\]"    # cyan
local W="\[\033[0;37m\]"    # white

# empahsized (bolded) colors
local EmK="\[\033[1;30m\]"
local EmR="\[\033[1;31m\]"
local EmG="\[\033[1;32m\]"
local EmY="\[\033[1;33m\]"
local EmB="\[\033[1;34m\]"
local EmM="\[\033[1;35m\]"
local EmC="\[\033[1;36m\]"
local EmW="\[\033[1;37m\]"

# background colors
local BgK="\[\033[40m\]"
local BgR="\[\033[41m\]"
local BgG="\[\033[42m\]"
local BgY="\[\033[43m\]"
local BgB="\[\033[44m\]"
local BgM="\[\033[45m\]"
local BgC="\[\033[46m\]"
local BgW="\[\033[47m\]"

local UC=$W                 # user's color
[ $UID -eq "0" ] && UC=$R   # root's color
local HC=$EmY

if [ -e .server_colors ]
then
    source .server_colors;
fi

# without colors: PS1="[\u@\h \${NEW_PWD}]\\$ "
# extra backslash in front of \$ to make bash colorize the prompt

PS1="${EmK}\n\[${HC}\d ${HC}\t${EmK}\] \n${EmK}\[${UC}\u${EmK}@${UC}\h ${EmB}\${NEW_PWD}${EmK}\] ${W}\\$ ${NONE}"

}

PROMPT_COMMAND=bash_prompt_command
bash_prompt
unset bash_prompt
